import { Metadata } from "next";

export const metadata : Metadata = {
  title: {
    default:"Next.js Tuto",
    template:"%s | NextJs"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "lightgrey", padding: "1rem" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
